version: "3"

services:
  app:
    build:
      context: ../
      dockerfile: deployment/Dockerfile
    container_name: medline_backend_app

    entrypoint: [ "./wait-for-it.sh", "postgres:5432", "--", "./main" ]
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - ../.env
    networks:
      - backend

  postgres:
    image: postgres:14-bullseye
    container_name: medline_backend_postgres
    hostname: postgres

    restart: always
    ports:
      - "5432:5432"
    expose:
      - "5432"
    env_file:
      - ../.env
    volumes:
      - "pg-data:/var/lib/postgresql/medline-backend/data"
    networks:
      - backend

networks:
  backend:

volumes:
  pg-data: